# NumPy Arrays

In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]

### One Dimensional Array (Vector)

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

### Two Dimensional Array (Matrix)

In [7]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
np.array(my_mat) #Note the two sets brackets on 2D array output

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Generating Arrays

In [12]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
#Generate array of random samples over a UNIFORM distribution
np.random.rand(5)

array([0.64815506, 0.72147613, 0.03334338, 0.2095923 , 0.05715197])

In [22]:
np.random.rand(5,5)

array([[0.04747698, 0.95951475, 0.2868191 , 0.05552472, 0.82600113],
       [0.61899968, 0.71659489, 0.0052837 , 0.00095993, 0.66709406],
       [0.76464409, 0.57663371, 0.85997236, 0.6025871 , 0.80139263],
       [0.60523787, 0.39867279, 0.88584483, 0.2563353 , 0.6838786 ],
       [0.91804323, 0.12705271, 0.69777665, 0.39496331, 0.47221418]])

In [23]:
#Generate array of random samples over a NORMAL distribution
np.random.randn(2)

array([ 0.044479  , -0.92358594])

In [24]:
np.random.randn(4,4)

array([[-0.05792698, -0.26953662, -0.71448669, -1.11709644],
       [ 0.62307412, -0.7271629 , -0.27082523,  0.75955764],
       [ 0.91661225,  0.61514021,  0.55651546, -0.59628142],
       [ 1.17399403,  0.55463851,  0.4411775 , -0.86476752]])

In [25]:
np.random.randint(1, 100)

9

In [26]:
np.random.randint(1,100,10)

array([81,  7, 91, 63, 51, 69,  7, 29, 32, 59])

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr = np.random.randint(0,50,10)

In [31]:
ranarr

array([49, 39,  5,  8,  1, 24, 16,  1, 11, 32])

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
#Return max value in array
ranarr.max()

49

In [36]:
#Return min value in array
ranarr.min()

1

In [35]:
#Return index value of max number
ranarr.argmax() 

0

In [37]:
arr.shape

(25,)

In [41]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr.shape

(5, 5)

In [40]:
arr.dtype

dtype('int64')