# NumPy Indexing and Selection

In [5]:
import numpy as np

In [6]:
arr = np.arange(0,11)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[8]

8

In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5] = 100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_arr = arr[0:6]

In [17]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [18]:
slice_of_arr[:] = 99

In [19]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [20]:
#Note that the broadcasting of slice_of_arr also change the original array arr
#NumPy will not automatically set copies of arrays
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
#Need to specify copy
arr_copy = arr.copy()

In [22]:
arr_copy[:] = 100

In [23]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [24]:
#Note no change on arr
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### 2D Array (Matrix)

In [25]:
arr_2d = np.array([[5, 10, 15], [20,25,30], [35,40,45]])

In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d[0][0]

5

In [28]:
arr_2d[0][2]

15

In [29]:
arr_2d[2][2]

45

In [30]:
#2nd row (index 1)
arr_2d[1]

array([20, 25, 30])

In [31]:
#Can also use single bracket with comma notation to pull values from matrix 
arr_2d[1,2]

30

In [34]:
#Rows 0 to 2 (excluding 2)
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [33]:
#Rows 0 to 2 (excluding 2)
#Columns 1 to 2
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [38]:
arr_2d[1, :2]

array([20, 25])

In [41]:
arr_2d[1:, 0:2]

array([[20, 25],
       [35, 40]])

### Conditional Selection

In [42]:
arr = np.arange(0,11)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
bool_arr = arr > 5

In [46]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [47]:
#Only return instances where boolean is true
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [48]:
#In one line
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [49]:
arr[arr<5]

array([0, 1, 2, 3, 4])

### Practice

In [56]:
my_arr = np.arange(50).reshape(5,10)

In [57]:
my_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [58]:
my_arr[2:4, 2:5]

array([[22, 23, 24],
       [32, 33, 34]])

In [59]:
my_arr[3:, 7:9]

array([[37, 38],
       [47, 48]])